apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama
spec:
  serviceUnhealthySecondThreshold: 900 # Config for the health check threshold for Ray Serve applications. Default value is 900.
  deploymentUnhealthySecondThreshold: 300 # Config for the health check threshold for Ray dashboard agent. Default value is 300.
  serveConfigV2: |
    applications:
      - name: llama
        import_path: llama-2:deployment
        runtime_env:
          working_dir: "https://github.com/krickwix/rayserve-examples/archive/refs/heads/main.zip"
  rayClusterConfig:
    # rayVersion: '2.7.0' # Should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      # Pod template
      template:
        spec:
          containers:
          - name: ray-head
            image: krickwix/ray-vllm:latest
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
            resources:
              limits:
                cpu: "2"
                memory: "8G"
              requests:
                cpu: "2"
                memory: "8G"
            env:
              - name: RAY_GRAFANA_IFRAME_HOST
                value: http://127.0.0.1:3000
              - name: RAY_GRAFANA_HOST
                value: http://prometheus-grafana.prometheus-system.svc:80
              - name: RAY_PROMETHEUS_HOST
                value: http://prometheus-kube-prometheus-prometheus.prometheus-system.svc:9090
          volumes:
            - name: ray-logs
              emptyDir: {}
    workerGroupSpecs:
    # The pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 10
      groupName: gpu-group
      rayStartParams: {}
      # Pod template
      template:
        spec:
          containers:
          - name: ray-worker
            image: krickwix/ray-vllm:latest
            resources:
              limits:
                cpu: 64
                memory: "192G"
                nvidia.com/gpu: 8
              requests:
                cpu: 3
                memory: "12G"
                nvidia.com/gpu: 8
            volumeMounts:
              - name: datasets-volume
                mountPath: /opt/data
            env :
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
          # Please add the following taints to the GPU node.
          tolerations:
            - key: "ray.io/node-type"
              operator: "Equal"
              value: "worker"
              effect: "NoSchedule"
          volumes:
            - name: datasets-volume
              persistentVolumeClaim:
                claimName: efs-pvc
